/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cal */

#ifndef _Included_cal
#define _Included_cal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cal
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cal_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
